COST-1575: Update OCP-on-Cloud calculations for distribution type (Trino)
project-koku/koku pull request #3066
Opened 2021-08-11 18:36 UTC by myersCody

TODO: Smoke tests

2021-08-12 03:24 UTC, myersCody commented
Smoke Tests:
```
ERROR lib64/python3.6/site-packages/iqe_cost_management/tests/rest_api/v1/test_tagging.py::test_api_ocp_on_azure_tag_filtered_project_false - wait_for.TimedOutError: Could not do 'function check_ingest_complete()' at /iqe_venv/lib64/py...
ERROR lib64/python3.6/site-packages/iqe_cost_management/tests/rest_api/v1/test_tagging.py::test_api_ocp_on_azure_tagging_report_filter_match_date_range - wait_for.TimedOutError: Could not do 'function check_ingest_complete()' at /iqe_v...
=========================================================================== 12 failed, 5189 passed, 201 skipped, 638 deselected, 635 errors in 6351.82s (1:45:51) ============================================================================
There is a test failing in your suite. Debug it running:
		curl -L https://url.corp.redhat.com/iqe-sh > iqe.sh && chmod +x iqe.sh
		ENV_FOR_DYNACONF=local IQE_IMAGE=docker-registry.upshift.redhat.com/insights-qe/iqe-tests:cost_management IQE_TESTS_LOCAL_CONF_PATH=/iqe_conf ./iqe.sh tests plugin cost_management --pdb
(koku) bash-3.2$
```
Don't think these are related to my changes, but gonna look into it more tomorrow.

2021-08-12 17:48 UTC, myersCody commented
/retest

2021-08-16 19:21 UTC, adberglund requested changes
Just a little change and this should be 👌

2021-08-16 19:21 UTC, adberglund commented on koku/masu/processor/ocp/ocp_cloud_parquet_summary_updater.py
> +                    distribution,
In this case, we want to check the distribution on the associated OpenShift cluster's cost model, *not* the cost model for the cloud source. We still get the markup from the cloud source, though.

2021-08-18 14:15 UTC, adberglund approved these changes

2021-08-19 19:15 UTC, merged