[Cost-1810]Can't access nodes/projects resource-types when rbac is restricted to a cluster
project-koku/koku pull request #3097
Opened 2021-08-27 20:30 UTC by Fozzywozzybear

This fix allows users that have set cluster restrictions to now see the proper data when they hit the resource-types/openshift-projects/ and openshift-nodes/.
steps to reproduce
1. Make a load customer data
2. Set rbac restrictions for openshift-cluster.
3. Hit the resource-type/openshift-projects/ or /resource-type/openshift-nodes/ 
4. The data returned should be related to that cluster that is set in RBAC

Please reach out to me or QA for any more details 
Jira ticket 
https://issues.redhat.com/browse/COST-1810
--- All Smokes pass ---

2021-09-01 22:20 UTC, maskarb requested changes

2021-09-01 22:20 UTC, maskarb commented on koku/api/resource_types/openshift_projects/view.py
> +                query_holder = self.queryset.filter(cluster_id__in=user_access)
Is this correct? Shouldn't it be:
```suggestion
                query_holder = self.queryset.filter(namespace__in=user_access)
```

2021-09-02 13:50 UTC, maskarb commented
/retest

2021-09-16 20:42 UTC, Fozzywozzybear commented
/retest

2021-09-16 21:27 UTC, maskarb commented on koku/api/resource_types/test/tests_views.py
> -
Why was this test removed?

2021-09-16 21:32 UTC, Fozzywozzybear commented on koku/api/resource_types/test/tests_views.py
> -
It was an accident, good catch !

2021-09-16 21:32 UTC, Fozzywozzybear commented on koku/api/resource_types/test/tests_views.py
> -
It has been added back

2021-09-17 06:03 UTC, lcouzens commented
/retest

2021-09-17 10:27 UTC, lcouzens commented
/retest

2021-09-18 16:46 UTC, lcouzens commented
/retest

2021-09-18 17:57 UTC, lcouzens commented
/retest

2021-09-22 20:55 UTC, Fozzywozzybear commented
/retest

2021-09-23 17:09 UTC, Fozzywozzybear commented
/retest

2021-09-24 11:01 UTC, lcouzens commented
/retest

2021-09-24 12:52 UTC, lcouzens commented
/retest

2021-09-24 21:30 UTC, Fozzywozzybear commented
/retest

2021-09-24 21:53 UTC, Fozzywozzybear commented
/retest

2021-09-30 18:10 UTC, lcouzens approved these changes
lgtm

2021-09-30 18:23 UTC, merged