Cost 2037 ocp aws use ocp trino table
project-koku/koku pull request #3301
Opened 2021-11-18 19:45 UTC by adberglund

## Summary
This switches to using two managed tables to step through the OCP on AWS calculations.

2021-12-02 14:44 UTC, Red-HAP submitted a review, later dismissed

2021-12-03 15:42 UTC, myersCody requested changes

2021-12-03 15:42 UTC, myersCody commented on koku/masu/database/presto_sql/reporting_ocpawscostlineitem_daily_summary.sql
> +    {{cluster_id}} as cluster_id,
I think you may need to replace the `{{cluster_id}}` & `{{cluster_alias}}` here as well.

2021-12-06 14:56 UTC, myersCody approved these changes

2021-12-06 15:51 UTC, merged