COST-1986: Remove deprecated project from gcp endpoints.
project-koku/koku pull request #3337
Opened 2021-12-08 15:46 UTC by myersCody

Clean up from the naming collision problem we had while working on OCP on GCP
- https://issues.redhat.com/browse/COST-1986

2021-12-09 16:31 UTC, myersCody commented
/retest

2022-01-11 14:30 UTC, maskarb requested changes
One nit-pick:

2022-01-11 14:30 UTC, maskarb commented on koku/api/tags/gcp/queries.py
>      # TODO: COST-1986
Can we remove this comment?

2022-01-12 12:10 UTC, lcouzens approved these changes
LGTM, the last smoke run had 4 failures but speaking to QE they are expected on main anyway.

2022-01-12 15:56 UTC, merged