COST-2106: Remove unnecessary GCP partables.
project-koku/koku pull request #3401
Opened 2022-01-14 15:33 UTC by myersCody

In an effort to do only additive changes I am gonna do this issue in two prs. The [first pull request](https://github.com/project-koku/koku/pull/3400) removed the unnecessary GCP partables from the provider map. When no endpoint in production can attempt to pull data from these tables, we can merge in the 2nd pull request (this one) to delete the tables.

2022-01-19 14:35 UTC, myersCody commented
Blocked by: https://github.com/project-koku/koku/pull/3408

2022-01-21 19:16 UTC, myersCody commented
/retest

2022-01-24 16:26 UTC, Red-HAP approved these changes

2022-01-24 18:16 UTC, maskarb requested changes

2022-01-24 18:16 UTC, maskarb commented on koku/reporting/provider/gcp/models.py
> -    "reporting_gcp_compute_summary_by_project_p",
Let's move the deletions from `UI_SUMMARY_TABLES` to a separate PR and ship to prod before merging these migrations.

2022-01-25 14:11 UTC, maskarb approved these changes

2022-01-26 15:30 UTC, maskarb approved these changes

2022-01-26 15:45 UTC, merged