[COST-2352] raw daily summary deletes
project-koku/koku pull request #3484
Opened 2022-02-22 21:15 UTC by adberglund

Fixes [COST-2352](https://issues.redhat.com/browse/COST-2352)

Changes proposed in this PR:
* Use direct SQL statements to delete from the daily summary tables on the Trino path

Testing Instructions:
1. Run standard load test customer data flow

2022-02-22 21:43 UTC, Red-HAP requested changes

2022-02-22 21:43 UTC, Red-HAP commented on koku/masu/database/report_db_accessor_base.py
> +        msg = f"Deleting records from {table} from {start_date} to {end_date}"
Shouldn't `{table}` be `{table._meta.db_table}`

2022-02-22 21:43 UTC, Red-HAP commented on koku/masu/database/report_db_accessor_base.py
> +        self._execute_raw_sql_query(table, sql, start_date, end_date)
```suggestion
        sql = f"""
            DELETE FROM {table._meta.db_table}
            WHERE source_uuid = %(source_uuid)s::uuid
                AND usage_start >= %(start_date)s::date
                AND usage_start <= %(end_date)s::date
        """
        if filters:
            filter_list = [f"AND {k} = %s" for k in filters]
            sql += "\n".join(filter_list)
        else:
            filters = {}
        filters["source_uuid"] = source_uuid
        filters["start_date"] = source_date
        filters["end_date"] = end_date

        self._execute_raw_sql_query(table, sql, start_date, end_date, bind_params=filters)
```

2022-02-23 16:24 UTC, adberglund commented on koku/masu/database/report_db_accessor_base.py
> +        msg = f"Deleting records from {table} from {start_date} to {end_date}"
```suggestion
        msg = f"Deleting records from {table._meta.db_table} from {start_date} to {end_date}"
```

2022-02-23 16:43 UTC, adberglund commented on koku/masu/database/report_db_accessor_base.py
> +        filters["start_date"] = source_date
```suggestion
        filters["start_date"] = start_date
```

2022-02-23 18:27 UTC, Red-HAP approved these changes

2022-02-23 21:00 UTC, Red-HAP approved these changes

2022-02-23 21:20 UTC, merged