Create rates dictionary for currency
project-koku/koku pull request #3707
Opened 2022-06-14 14:27 UTC by shannon-donahue

Fixes [COST-####](https://issues.redhat.com/browse/COST-####)

Changes proposed in this PR:
*
*

Testing Instructions:
1. Run `this command` ...
2. Ingest this data `with this other command` ...
3. Expect to see this result:
   ```
   GET http://localhost:8000/api/endpoint

   {json: response}
   ```
4.
5.

---
Additional Context:

2022-06-14 18:24 UTC, InsightsDroid commented
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
be79ce08-09ef-4f94-a430-07e9387983ba

2022-06-14 19:08 UTC, Fozzywozzybear approved these changes
LGTM!

2022-06-14 19:15 UTC, Red-HAP requested changes

2022-06-14 19:15 UTC, Red-HAP commented on koku/api/currency/utils.py
> +                currency_dict[code] = float(1 / rates[base_currency])
float is imprecise. I'd suggest using decimal.Decimal
The math could be different in subsequent runs.

2022-06-15 18:14 UTC, lcouzens approved these changes
Great job!

2022-06-15 20:02 UTC, merged