COST-2881: Purge trino files internal endpoint.
project-koku/koku pull request #3813
Opened 2022-08-12 05:43 UTC by myersCody

## Jira Ticket

[COST-2881](https://issues.redhat.com/browse/COST-2881)

## Description

This change will ...

## Testing

1. Checkout Branch
2. Restart Koku
3. Hit endpoint or launch shell
    1. You should see ...
4. Do more things...

## Notes

...

2022-08-15 10:54 UTC, lcouzens requested changes
We need to update the masu openapi spec + add unit tests.

2022-08-15 10:54 UTC, lcouzens commented on koku/masu/api/purge_trino_files.py
> +        bill_date - usually the start of the month example 08-12-2022
I feel like this should be yyyy-mm-dd

2022-08-15 10:54 UTC, lcouzens commented on koku/masu/database/report_manifest_db_accessor.py
> +        Deletes a specific manifest given manifest_id & provider_uui
provider_uuid

2022-08-15 23:38 UTC, myersCody commented
/retest

2022-08-16 00:19 UTC, myersCody commented
> We need to update the masu openapi spec + add unit tests.

Thanks for the early feedback, I went ahead and address these while I was working on the endpoint. I should be ready to move this out of draft later tonight after checking the smoke tests.

2022-08-16 11:00 UTC, lcouzens submitted a review, later dismissed

2022-08-16 11:13 UTC, lcouzens commented
/retest

2022-08-16 12:07 UTC, lcouzens commented
Failing smoke tests change on each run, sometimes time-outs sometimes not on different tests. Either way the smoke tests really don't test anything in this pr directly so I think this is fine to move forward.

2022-08-16 14:01 UTC, myersCody commented
Smoke test: https://ci.ext.devshift.net/job/project-koku-koku-pr-check/6330/

We are certain the one failure is unrelated to these changes.

2022-08-16 15:10 UTC, lcouzens approved these changes

2022-08-16 15:16 UTC, merged