Initial sql/api work for 3096
project-koku/koku pull request #3989
Opened 2022-11-03 20:28 UTC by lcouzens

## Jira Ticket

[COST-3096](https://issues.redhat.com/browse/COST-3096)

## Description

This change will ...

## Testing

1. Checkout Branch
2. Restart Koku
3. Hit endpoint or launch shell
    1. You should see ...
4. Do more things...

## Notes

...

2022-11-11 09:07 UTC, lcouzens commented
Amazing only one Smoke failure and it's expected from main test_api_ocp_on_aws_source_raw_calc

2022-11-11 18:30 UTC, maskarb requested changes

2022-11-11 18:30 UTC, maskarb commented on koku/api/report/queries.py
> +            ):
```suggestion
            if is_grouped_by_project(self.parameters):
```

2022-11-11 18:54 UTC, maskarb commented
Is `category` only valid when `group_by[project]` is used? Should it be a validation error if `category` is used when we are not grouping by project?

2022-11-11 19:47 UTC, lcouzens commented on koku/api/query_params.py
> +    def category(self):
Thanks Michael, I figured this was wrong and you would set me straight. :bow:

2022-11-11 21:03 UTC, maskarb submitted a review, later dismissed
lgtm!

2022-11-14 11:33 UTC, esebesto approved these changes

2022-11-14 11:36 UTC, merged