PR Check Enhancement
project-koku/koku pull request #4400
Opened 2023-05-30 15:09 UTC by maknop

## Jira Ticket

[RHCLOUD-24752](https://issues.redhat.com/browse/RHCLOUD-24752)

## Description

This change will convert the `pr_check.sh` to the `Jenkinsfile` script.

2023-05-30 17:10 UTC, maskarb commented
/retest

2023-05-30 18:08 UTC, maknop commented
/retest

2023-05-30 18:48 UTC, maknop commented
/retest

2023-05-30 18:52 UTC, maknop commented
/retest

2023-05-30 18:53 UTC, maknop commented
/retest

2023-05-30 19:17 UTC, maskarb commented
/retest

2023-05-30 19:20 UTC, maknop commented
/retest

2023-05-31 17:05 UTC, maskarb commented
/retest

2023-05-31 17:37 UTC, maknop commented
/retest

2023-05-31 17:48 UTC, maknop commented
/retest

2023-05-31 17:54 UTC, maknop commented
/retest

2023-06-07 16:44 UTC, maknop commented
/retest

2023-06-07 16:52 UTC, maknop commented
/retest

2023-06-14 10:01 UTC, Victoremepunto requested changes

2023-06-14 11:01 UTC, Victoremepunto commented on Jenkinsfile
> +                        if egrep 'aws-smoke-tests' ${LABELS_DIR}/github_labels.txt &>/dev/null
This sets `IQE_FILTER_EXPRESSION` and optionally `IQE_MARKER_EXPRESSION` env variables, to affect the behavior of the `Run Smoke Tests` Stage later on, but I don't think the environment variables remain set between stages.

2023-06-22 09:01 UTC, Victoremepunto commented
/retest

2023-06-22 12:43 UTC, Victoremepunto commented
/retest

2023-06-28 16:40 UTC, Victoremepunto approved these changes

2023-06-28 16:50 UTC, maskarb approved these changes

2023-06-28 18:52 UTC, merged