[COST-3896] Add product/physicalCores and identity/TimeInterval to the AWS Line Items
project-koku/koku pull request #4435
Opened 2023-06-07 22:06 UTC by djnakabaale

## Jira Ticket

[COST-3896](https://issues.redhat.com/browse/COST-3896)

## Description

This change will add relevant SWATCH columns to `aws_line_items`

## Testing

1. Checkout Branch
2. Restart Koku
3. Hit endpoint or launch shell
    1. You should see ...
4. Do more things...

## Notes

...
Requires https://github.com/project-koku/nise/pull/453 for appropriate test data

2023-06-12 14:14 UTC, lcouzens commented on koku/masu/util/aws/aws_post_processor.py
> +        "identity/TimeInterval",
Also is `product/physicalCore` even a real column? :grimacing:

2023-06-12 14:19 UTC, lcouzens requested changes
We need to check that `product/physicalCores` thing since thats not a real column in any of the real AWS data I've looked at. We have `product/vcpus` maybe we want that? Either way we dont want to add this column to the required ingress columns since thats going to likely break customer filtered data posts today.

2023-06-13 14:19 UTC, djnakabaale commented on koku/masu/util/aws/aws_post_processor.py
> +        "identity/TimeInterval",
😃 `product/physicalCores` is a real [column in the AWS Cost and Usage Reports](https://docs.aws.amazon.com/cur/latest/userguide/product-columns.html#product-details-P)

2023-06-13 14:23 UTC, djnakabaale commented
> We need to check that `product/physicalCores` thing since thats not a real column in any of the real AWS data I've looked at. We have `product/vcpus` maybe we want that? Either way we dont want to add this column to the required ingress columns since thats going to likely break customer filtered data posts today.

This is addressed in these comments

https://github.com/project-koku/koku/pull/4435#discussion_r1228210975 and https://github.com/project-koku/koku/pull/4435#discussion_r1228210463

2023-06-13 18:13 UTC, djnakabaale commented
/retest

2023-06-14 10:16 UTC, lcouzens approved these changes

2023-06-23 11:56 UTC, djnakabaale commented
/retest

2023-06-26 13:59 UTC, merged