Add settings to rbac python file.
project-koku/koku pull request #4586
Opened 2023-07-17 19:02 UTC by myersCody

## Jira Ticket

[COST-####](https://issues.redhat.com/browse/COST-####)

## Description

This change will ...

## Testing

1. Checkout Branch
2. Restart Koku
3. Hit endpoint or launch shell
    1. You should see ...
4. Do more things...

## Notes

...

2023-07-17 20:59 UTC, maskarb reviewed
This looks good, but we ought to add back the `if settings.ENHANCED_ORG_ADMIN and request.user.admin:` to the `SettingsAccessPermission` class.

2023-07-18 13:57 UTC, samdoran requested changes

2023-07-18 13:57 UTC, samdoran commented on koku/koku/test_rbac.py
> +    return default
You can use the `update()` method to modify the values in `default` or the `|` operator to return a new dictionary with merged values. 
```suggestion
    return default | access_dict
```

2023-07-18 13:57 UTC, samdoran commented on koku/koku/test_rbac.py
> +    """Helper function for defaulting access permissions."""
```suggestion
def create_default_access(access_dict=None, default_write=None):
    """Helper function for defaulting access permissions."""
    if access_dict is None:
        access_dict = {}
       
   if default_write is None:
       default_write = {"write": [], "read": []}, default_read={"read": []}
```

2023-07-18 15:06 UTC, maskarb commented
> > This looks good, but we ought to add back the `if settings.ENHANCED_ORG_ADMIN and request.user.admin:` to the `SettingsAccessPermission` class.
> 
> I am pretty certain this would cause the current ddf settings to have a 403 again. The only reason that got resolved yesterday was because I removed the `settings.ENHANCED_ORG_ADMIN` check.
> 
> So, what I am trying to do is build settings permissions that will work for the current DDF settings & for the new settings endpoint.

I am 99% sure the reason we saw the 403 was because the `settings` in resource types was missing. An org admin has the `Cost Administrator` role automatically which includes the `cost-management:*:*` access. When we look up this access, we convert the wildcards [here](https://github.com/project-koku/koku/blob/main/koku/koku/rbac.py#L119) to give that user access to all the resource types. Since settings was missing, we were returning the 403.

2023-07-18 17:50 UTC, maskarb approved these changes

2023-07-18 18:26 UTC, myersCody commented on koku/koku/test_rbac.py
> +        default_write = {"write": [], "read": []}
So, I tried your suggestion of combining them, but the test starting failing. I need to be able to set them independently in certain places in the test:

https://github.com/project-koku/koku/pull/4586/files#diff-e99710acde7df448c3ce00e9fdf21f96a49c90549781c51d57f9a4292423df13R374

2023-07-18 18:27 UTC, merged