[COST-3976] Remove deprecated tag models.
project-koku/koku pull request #4605
Opened 2023-07-29 20:14 UTC by myersCody

## Jira Ticket

[COST-3976](https://issues.redhat.com/browse/COST-3976)

## Description

This change will ...

## Testing

1. Checkout Branch
2. Restart Koku
3. Hit endpoint or launch shell
    1. You should see ...
4. Do more things...

## Notes

...

2023-07-29 20:15 UTC, myersCody commented
waiting for new settings to launch.

2023-09-07 10:59 UTC, lcouzens requested changes
I think this looks good for the most part, just need to get that little migration typo fix I think. Thanks for the hard work Cody! :bow:

2023-09-07 10:59 UTC, lcouzens commented on koku/reporting/migrations/0305_pvc.py
> +        ("reporting", "0305_pvc"),
Why is this referencing itself :sweat_smile: Feels like a typo

2023-09-19 18:43 UTC, lcouzens approved these changes

2023-11-01 18:06 UTC, lcouzens approved these changes

2023-11-02 18:18 UTC, merged