[COST-5011] Limit OS disk correlation to pod data source rows
project-koku/koku pull request #5106
Opened 2024-05-14 20:11 UTC by myersCody

## Jira Ticket

[COST-5011](https://issues.redhat.com/browse/COST-5011)

## Description

This change will limit OS disk correlation to the POD data source rows. 

## Testing
- https://gitlab.cee.redhat.com/insights-qe/iqe-cost-management-plugin/-/merge_requests/1970/diffs

## Release Notes
- [ ] proposed release note

```markdown
* [COST-5011](https://issues.redhat.com/browse/COST-5011) Limit OS disk correlation to pod data source rows
```

2024-05-14 20:23 UTC, myersCody commented on koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
> +                (LOWER(CONCAT(ocp.node, '_OSDisk')) = LOWER(azure.resource_id)) AND ocp.data_source = 'Pod'
fine with me 👍

2024-05-14 20:49 UTC, maskarb approved these changes

2024-05-15 12:55 UTC, lcouzens requested changes

2024-05-15 12:55 UTC, lcouzens commented on koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
> +                (replace(lower(azure.resource_id), "_osdisk", "") = lower(ocp.node) AND ocp.data_source = 'Pod')
```suggestion
                (replace(lower(azure.resource_id), '_osdisk', '') = lower(ocp.node) AND ocp.data_source = 'Pod')
```

2024-05-15 12:56 UTC, esebesto approved these changes

2024-05-15 12:58 UTC, lcouzens approved these changes

2024-05-15 13:41 UTC, merged