[COST-4745] Add `data_transfer_direction` to GCP network costs to Trino tables
project-koku/koku pull request #5130
Opened 2024-05-22 17:12 UTC by samdoran

## Jira Ticket

[COST-4745](https://issues.redhat.com/browse/COST-4745)

## Description

Add `data_transfer_direction` to Trino tables for tracking GCP network costs.

## Testing

1. Checkout Branch
2. Delete existing data
3. Load OCP on GCP data

## Release Notes
- [ ] proposed release note

```markdown
* [COST-4745](https://issues.redhat.com/browse/COST-4745) Add `data_transfer_direction` for GCP network costs to Trino tables 
```

2024-06-03 17:01 UTC, cgoodfred commented on koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
> +    data_transfer_direction varchar,
```suggestion
```
This needs to be added within the creation of `reporting_ocpgcpcostlineitem_project_daily_summary` not `gcp_openshift_daily_tag_matched_temp`
Relevant reference: https://github.com/project-koku/koku/pull/5058/files#diff-d93349900fcf45dec5595ef5c01c5f394889315c807c935062130dcc6b538f8cR138

2024-06-04 12:05 UTC, cgoodfred approved these changes

2024-06-13 21:33 UTC, cgoodfred requested changes
This was still added to the wrong table, it should have been added to the non temp table. The same line in the link here: https://github.com/project-koku/koku/pull/5058/files#diff-d93349900fcf45dec5595ef5c01c5f394889315c807c935062130dcc6b538f8cR138

2024-06-13 21:37 UTC, samdoran commented
I'll fix this up tomorrow.

2024-06-14 15:37 UTC, samdoran commented
I added the field to the correct table.

2024-06-18 13:44 UTC, cgoodfred approved these changes

2024-06-18 17:04 UTC, merged