[COST-4904] Update aws resource matching to include csi_volume_handle
project-koku/koku pull request #5255
Opened 2024-08-08 17:21 UTC by myersCody

## Jira Ticket

[COST-4904](https://issues.redhat.com/browse/COST-4904)

## Description

This change will update the aws resource matching to utilize the csi_volume_handle

## Testing

1. Checkout Branch
2. Run load test customer data for AWS
3. Run this trino query:
```
select lineitem_resourceid, resource_id_matched  from aws_openshift_daily where lineitem_resourceid like 'vol-%' group by lineitem_resourceid, resource_id_matched;
```
Results:
```
 lineitem_resourceid | resource_id_matched
---------------------+---------------------
 vol-12345672        | true
 vol-12345673        | true
 vol-12345671        | true
 vol-12345674        | true
 ```
 ^ This used to return false

## Release Notes
- [ ] proposed release note

```markdown
* [COST-####](https://issues.redhat.com/browse/COST-####) Fix some things
```

2024-08-13 18:38 UTC, lcouzens submitted a review, later dismissed

2024-08-14 18:00 UTC, myersCody commented
So, there is an additional edge case to consider with these changes. Now the operator is already release, so some customer may have already upgraded. That means that these resources will have resource_id_matched value of True, which excludes them from the tag matching logic [here](https://github.com/project-koku/koku/blob/main/koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql#L337).

In order to maintain the same logic until I get the unattributed storage pieces delivered, we will need to still consider the csi volume handle resources for tag matching. Otherwise cost correlation could drop unexpectedly when we roll these changes out.

2024-08-14 18:08 UTC, myersCody commented
```
trino:org1234567> select distinct matched_tag, resource_id from aws_openshift_daily_tag_matched_temp where resource_id like 'vol-%';
        matched_tag        | resource_id
---------------------------+--------------
 "storageclass": "delta"   | vol-12345672
 "storageclass": "epsilon" | vol-12345673
 ```

2024-08-14 18:12 UTC, lcouzens requested changes

2024-08-14 18:12 UTC, lcouzens commented on koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
> +            FROM hive.org1234567.openshift_storage_usage_line_items_daily as ocp
I'm pretty sure this is wrong :teehee:

2024-08-14 18:31 UTC, myersCody commented on koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
> +            FROM hive.org1234567.openshift_storage_usage_line_items_daily as ocp
good catch

2024-08-15 17:19 UTC, myersCody commented
/retest

2024-08-16 13:55 UTC, myersCody commented
/retest

2024-08-20 08:11 UTC, lcouzens approved these changes
Left one comment, which tbh I can deal with afterwards. So looks good to me.

2024-08-20 08:11 UTC, lcouzens commented on koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
> +    sum(aws.lineitem_unblendedcost) as unblended_cost,
You will probably merge your PR first but as a side note and reminder to myself I guess. We will need to update the unblended/blended inserts in here for negation costs. Following this https://github.com/project-koku/koku/pull/5252

2024-08-20 12:35 UTC, merged