handle Customer.DoesNotExist exception
project-koku/koku pull request #5431
Opened 2024-12-23 15:18 UTC by djnakabaale

## Jira Ticket

[COST-####](https://issues.redhat.com/browse/COST-####)

## Description

This change will ...

## Testing

1. Checkout Branch
2. Restart Koku
3. Hit endpoint or launch shell
    1. You should see ...
4. Do more things...

## Release Notes
- [ ] proposed release note

```markdown
* [COST-####](https://issues.redhat.com/browse/COST-####) Fix some things
```

2025-01-03 21:11 UTC, maskarb requested changes

2025-01-03 21:11 UTC, maskarb commented on koku/koku/middleware.py
> +                    return None
Why is this change here? We still return the Customer object for `GET` and `HEAD` requests, but this change undoes that. We *intentionally do not save a customer* for `GET` and `HEAD` requests.

2025-01-03 21:11 UTC, maskarb commented on koku/koku/middleware.py
> +                return None
What is the impact of returning None? Won't this just error somewhere else?

2025-01-06 20:14 UTC, djnakabaale commented on koku/koku/middleware.py
> +                return None
Yeah `None` maybe problematic else where like in some of the ProviderBuilder methods, returning an empty `Customer` object instead.

2025-01-08 17:59 UTC, maskarb commented on koku/koku/middleware.py
> +                return None
I'm not sure this is a good idea either? How does this resolve the issue that we're encountering? What is the impact of passing around an empty Customer object??

2025-01-14 15:19 UTC, maskarb approved these changes

2025-01-14 16:37 UTC, merged